trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr:
- master

stages:

- stage: build
  displayName: build

  variables:
    sdkVersion: 3.1.x
    solutionPath: .
    buildConfiguration: Release

  jobs:

  - job: build
    displayName: build

    pool:
      vmImage: ubuntu-latest

    steps:

    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: $(sdkVersion)
      displayName: dotnet $(sdkVersion)

    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        publishWebProjects: true
        arguments:
          --configuration $(buildConfiguration)
          --output $(Build.ArtifactStagingDirectory)/publish
        modifyOutputPath: false
        zipAfterPublish: false
      displayName: dotnet publish

    - publish: $(Build.ArtifactStagingDirectory)/publish
      artifact: app
      displayName: artifact publish app

  - job: test
    displayName: test

    pool:
      vmImage: ubuntu-latest

    steps:

    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: $(sdkVersion)
      displayName: dotnet $(sdkVersion)

    - script: dotnet test $(solutionPath)
        --configuration $(buildConfiguration)
        --collect "XPlat Code Coverage"
        --logger trx
        --results-directory $(Common.TestResultsDirectory)
      continueOnError: true
      displayName: dotnet test

    - task: PublishTestResults@2
      inputs:
        testRunner: VSTest
        testResultsFiles: $(Common.TestResultsDirectory)/*.trx
      displayName: test results build publish

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: $(Common.TestResultsDirectory)/*/coverage.cobertura.xml
      displayName: code coverage build publish

- stage: deploy
  displayName: deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn: build

  jobs:

  - deployment: deploy_dev
    displayName: deploy dev

    pool:
      vmImage: ubuntu-latest

    environment: dev

    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            artifact: app
            displayName: artifact download app

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: AzureRM
              azureSubscription: Pay-As-You-Go(0518cd5b-d389-4983-9496-cdcae31dcc60)
              appType: webApp
              WebAppName: restaurant-reviews-escalera
              packageForLinux: $(Pipeline.Workspace)/app
            displayName: azure app service deploy
