trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr:
- master

stages:

- stage: build

  variables:
    solutionPath: .
    buildConfiguration: Release

  jobs:

  - job: build

    pool:
      vmImage: ubuntu-latest

    steps:

    - script: dotnet build $(solutionPath) -c $(buildConfiguration)
      displayName: dotnet build

    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        publishWebProjects: true
        arguments: -c $(buildConfiguration) -o publish-output
        zipAfterPublish: false
      displayName: dotnet publish

    - publish: publish-output
      artifact: app
      displayName: Publish artifact app

  - job: test

    pool:
      vmImage: ubuntu-latest

    steps:

    - script: dotnet test $(solutionPath)
        --configuration $(buildConfiguration)
        --collect "XPlat Code Coverage"
        --logger trx
        --results-directory test-output
      continueOnError: true
      displayName: dotnet test

    - task: PublishTestResults@2
      inputs:
        testRunner: VSTest
        testResultsFiles: test-output/*.trx
      displayName: Publish test results to build

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: test-output/*/coverage.cobertura.xml
      displayName: Publish code coverage to build

- stage: deploy
  displayName: deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn: build

  jobs:

  - deployment: deploy-dev
    displayName: deploy dev

    variables:
      azureSubscription: Pay-As-You-Go(0518cd5b-d389-4983-9496-cdcae31dcc60)
      webAppName: restaurant-reviews-escalera

    pool:
      vmImage: ubuntu-latest

    environment: dev

    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            artifact: app
            displayName: Download app artifact

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: AzureRM
              azureSubscription: $(azureSubscription)
              appType: webApp
              WebAppName: $(webAppName)
              packageForLinux: $(Pipeline.Workspace)/app
            displayName: Deploy to Azure App Service
